"""Generate data.js from a '.xlsx' file. Only rerun when the data changes."""

import json
import math
import networkx as nx
from openpyxl import load_workbook

XLSX = "SNA_matrix.xlsx"
GRAPHS = ["ALL", "GG-EU", "GG-CH"]
N = 48
SPREAD = 900  # half-width in px of the box the nodes are laid out in
STRETCH = 1.6  # the layout comes out square but windows are wide: stretch along x
CORE = 0.6  # <1 opens up the crowded centre

wb = load_workbook(XLSX, read_only=True, data_only=True)

# Topics sheet: index -> concept name.
labels = {
    int(i): str(name)
    for i, name in wb["Topics"].iter_rows(max_row=N, max_col=2, values_only=True)
}


def read_matrix(sheet):
    """NxN matrix of ints, skipping the index row and column."""
    rows = sheet.iter_rows(min_row=2, max_row=N + 1, min_col=2, max_col=N + 1, values_only=True)
    return [[int(v or 0) for v in row] for row in rows]


# The matrices are symmetric: the diagonal is the node weight, the rest the edge weight,
# so the upper triangle is enough for the edges.
graphs = {}
for name in GRAPHS:
    m = read_matrix(wb[name])
    graphs[name] = {
        "weights": {str(i + 1): m[i][i] for i in range(N)},
        "edges": [[i + 1, j + 1, m[i][j]] for i in range(N) for j in range(i + 1, N) if m[i][j]],
    }

# Positions computed once on ALL and shared by all three, so nodes stay put when
# switching. Weighted, or the dense ALL collapses into a blob. Fixed seed => reproducible.
g = nx.Graph()
g.add_nodes_from(range(1, N + 1))
g.add_weighted_edges_from(graphs["ALL"]["edges"])
pos = nx.spring_layout(g, weight="weight", seed=42, iterations=200)

# The layout comes out crowded in the middle and nearly square, while windows are wide and
# cy.fit ends up driven by the height. Radial expansion (r -> r^CORE) opens the centre and
# leaves angles untouched, so clusters stay put; the x stretch fills the wasted width.
cx = sum(p[0] for p in pos.values()) / N
cy = sum(p[1] for p in pos.values()) / N
rmax = max(math.hypot(p[0] - cx, p[1] - cy) for p in pos.values())


def spread_out(p):
    dx, dy = p[0] - cx, p[1] - cy
    r = math.hypot(dx, dy)
    f = 0 if r == 0 else rmax * (r / rmax) ** CORE / r
    return (dx * f * STRETCH, dy * f)


pos = {i: spread_out(p) for i, p in pos.items()}

span = max(max(abs(c) for c in p) for p in pos.values())
nodes = [
    {
        "id": str(i),
        "label": labels[i],
        "x": round(pos[i][0] / span * SPREAD, 1),
        "y": round(pos[i][1] / span * SPREAD, 1),
    }
    for i in range(1, N + 1)
]

# One node and one graph per line: it is a generated file, but diffs stay readable.
nodes_js = ",\n  ".join(json.dumps(n, ensure_ascii=False) for n in nodes)
graphs_js = ",\n  ".join(f"{json.dumps(k)}: {json.dumps(v)}" for k, v in graphs.items())

with open("data.js", "w", encoding="utf-8") as f:
    f.write("// Generated by build_data.py - do not edit by hand.\n")
    f.write(f"const DATA = {{\n nodes: [\n  {nodes_js}\n ],\n graphs: {{\n  {graphs_js}\n }}\n}};\n")

print(f"data.js: {len(nodes)} nodes, " + ", ".join(f"{k} {len(v['edges'])} edges" for k, v in graphs.items()))
